[package]
name = "plot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colorgrad = "0.6.2"
csv = "1.3.0"
flate2 = "1.0.30"
geo = "0.28.0"
image = "0.25.1"
serde = { version = "1.0.202", features = ["derive"] }
